#!/usr/bin/env bash
# Shared: install the cron entry that keeps this machine in sync with GitHub.
# Runs sync-from-github.sh every 30 min.
# Idempotent — safe to re-run.

set -euo pipefail

REPO_PATH="${1:-$HOME/smorch-dev}"  # local path to smorch-dev repo
SYNC_CMD="bash $REPO_PATH/scripts/sync-from-github.sh >> $HOME/.claude/sync.log 2>&1"
CRON_COMMENT="# smorch-dev auto-sync (generated by install-cron-sync.sh)"
CRON_LINE="*/30 * * * * $SYNC_CMD"

log() { echo "  [install-cron-sync] $1"; }

# Check if already installed
EXISTING_CRON="$(crontab -l 2>/dev/null || echo "")"

if echo "$EXISTING_CRON" | grep -Fq "sync-from-github.sh"; then
  log "cron entry already present — skipping"
else
  {
    echo "$EXISTING_CRON"
    echo ""
    echo "$CRON_COMMENT"
    echo "$CRON_LINE"
  } | crontab -
  log "installed cron: every 30 min → $SYNC_CMD"
fi

# Also: drift check cron (calls smorch-brain's check-config-drift.sh if present)
BRAIN_CHECK="$HOME/smorch-brain/scripts/check-config-drift.sh"
if [ -f "$BRAIN_CHECK" ] && ! echo "$EXISTING_CRON" | grep -Fq "check-config-drift.sh"; then
  {
    crontab -l 2>/dev/null
    echo "# smorch-brain config drift check"
    echo "0 * * * * bash $BRAIN_CHECK >> $HOME/.claude/drift.log 2>&1"
  } | crontab -
  log "installed hourly config drift check"
fi

log "cron sync configured"
